services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "7543:5432"
    environment:
      POSTGRES_USER: Jonapost
      POSTGRES_PASSWORD: Jonapost
      POSTGRES_DB: sclass